# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0002_auto_20170204_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funciona',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
