# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0003_auto_20170207_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funciona',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 7, 16, 22, 57, 73777, tzinfo=utc)),
        ),
    ]
