# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0004_auto_20170207_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funciona',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
