# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0005_auto_20170208_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Capas_cedeus',
        ),
        migrations.DeleteModel(
            name='Capas_cigiden',
        ),
        migrations.DeleteModel(
            name='Capas_ocuc',
        ),
    ]
