# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0008_privacidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacidad',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
