# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0009_auto_20170412_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
