# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0010_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacidad',
            name='ide',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
