# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0012_categorias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
