# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ides', '0013_auto_20170515_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlPendientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('ide', models.CharField(max_length=200)),
                ('workspace', models.CharField(max_length=200)),
                ('datastore', models.CharField(max_length=200)),
                ('layer', models.CharField(max_length=400)),
                ('pendiente', models.BooleanField(default=True)),
            ],
        ),
    ]
